# Generated by Django 4.2.5 on 2023-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hhhjjhg', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
